export interface PersonalInfo {
  fullName: string;
  title: string;
  email: string;
  phone: string;
  location: string;
  website: string;
  linkedin: string;
  github: string;
  summary: string;
  profileImage?: string; // Base64 encoded or URL
}

export interface WorkExperience {
  id: string;
  company: string;
  role: string;
  location: string;
  startDate: string;
  endDate: string;
  current: boolean;
  description: string[]; // Bullets
}

export interface Education {
  id: string;
  school: string;
  degree: string;
  fieldOfStudy: string;
  location: string;
  startDate: string;
  endDate: string;
  current: boolean;
  description: string;
}

export interface SkillGroup {
  id: string;
  category: string;
  skills: string[];
}

export interface Project {
  id: string;
  name: string;
  description: string;
  url?: string;
  technologies: string[];
}

export interface ThemeColors {
  primary: string;      // Primary brand color (e.g. hex #1e3a8a)
  secondary: string;    // Secondary color (e.g. hex #4b5563)
  accent: string;       // Accent color (e.g. hex #f59e0b)
  background: string;   // Page background (e.g. hex #ffffff)
  textPrimary: string;  // Primary text color (e.g. #111827)
  textSecondary: string;// Secondary text (e.g. #4b5563)
  border: string;       // Border colors (e.g. #e5e7eb)
}

export interface ThemeConfig {
  fontSans: string;       // e.g. "Inter"
  fontDisplay: string;    // e.g. "Space Grotesk"
  fontMono: string;       // e.g. "JetBrains Mono"
  colors: ThemeColors;
  layoutStyle: "classic" | "modern" | "sidebar" | "minimal";
  fontSize: "sm" | "base" | "lg";
  spacing: "compact" | "normal" | "relaxed";
  customStylingTips?: string; // generated by AI
  pageSize?: "A4" | "A3" | "B3" | "B4" | "Letter" | "Legal"; // Standard page size options
}

export interface ResumeData {
  id: string;
  title: string;
  personalInfo: PersonalInfo;
  workExperience: WorkExperience[];
  education: Education[];
  skills: SkillGroup[];
  projects: Project[];
  themeConfig: ThemeConfig;
  templateId: string;
  createdAt: number;
  updatedAt: number;
  userId: string;
}

export const DEFAULT_THEME_COLORS: ThemeColors = {
  primary: "#1e3a8a", // Deep Blue
  secondary: "#0f766e", // Teal
  accent: "#f59e0b", // Amber
  background: "#ffffff",
  textPrimary: "#111827",
  textSecondary: "#4b5563",
  border: "#e5e7eb",
};

export const DEFAULT_THEME: ThemeConfig = {
  fontSans: "Inter",
  fontDisplay: "Inter",
  fontMono: "Courier",
  colors: DEFAULT_THEME_COLORS,
  layoutStyle: "modern",
  fontSize: "base",
  spacing: "normal",
  pageSize: "A4",
};

export const SAMPLE_RESUME: ResumeData = {
  id: "sample-resume",
  title: "My Professional Resume",
  personalInfo: {
    fullName: "Alex Rivera",
    title: "Senior Full-Stack Engineer",
    email: "alex.rivera@example.com",
    phone: "+1 (555) 019-2834",
    location: "San Francisco, CA",
    website: "https://alexrivera.dev",
    linkedin: "linkedin.com/in/alex-rivera",
    github: "github.com/alexrivera",
    summary: "Driven and innovative Full-Stack Engineer with 6+ years of experience designing, building, and deploying highly scalable cloud applications. Expert in React, Node.js, and cloud native architectures. Proven track record of leading cross-functional teams to deliver critical products ahead of schedule while maintaining high quality standards.",
    profileImage: "",
  },
  workExperience: [
    {
      id: "work-1",
      company: "TechNova Solutions",
      role: "Lead Full-Stack Engineer",
      location: "San Francisco, CA",
      startDate: "2023-01",
      endDate: "",
      current: true,
      description: [
        "Architected and launched a real-time collaborative dashboard using React and WebSockets, increasing daily active user engagement by 35%.",
        "Led a team of 4 engineers to migrate a legacy monolithic service to an AWS serverless architecture, reducing cloud infrastructure hosting costs by 42%.",
        "Established CI/CD deployment pipelines that cut release cycles from 2 weeks to multiple daily production deployments with zero downtime."
      ]
    },
    {
      id: "work-2",
      company: "Innovate Labs",
      role: "Senior Software Engineer",
      location: "Austin, TX",
      startDate: "2020-05",
      endDate: "2022-12",
      current: false,
      description: [
        "Developed and maintained critical payment processing APIs handling over $2M in daily transactions with 99.99% uptime.",
        "Optimized slow MongoDB database queries and implemented Redis caching, reducing API response latency by 60%.",
        "Mentored 3 junior developers and introduced rigorous peer code reviews to ensure code quality and knowledge sharing across the engineering group."
      ]
    }
  ],
  education: [
    {
      id: "edu-1",
      school: "University of California, Berkeley",
      degree: "Bachelor of Science",
      fieldOfStudy: "Computer Science",
      location: "Berkeley, CA",
      startDate: "2016-09",
      endDate: "2020-05",
      current: false,
      description: "Graduated with Honors. Specialization in Software Engineering and Distributed Systems. Active member of the Computer Science Undergraduate Association."
    }
  ],
  skills: [
    {
      id: "skill-1",
      category: "Languages",
      skills: ["TypeScript", "JavaScript", "Python", "SQL", "HTML5/CSS3"]
    },
    {
      id: "skill-2",
      category: "Frameworks & Tools",
      skills: ["React", "Node.js", "Express", "Next.js", "Tailwind CSS", "Git", "Docker"]
    },
    {
      id: "skill-3",
      category: "Cloud & Databases",
      skills: ["AWS (S3, Lambda, RDS)", "PostgreSQL", "MongoDB", "Redis", "Firebase"]
    }
  ],
  projects: [
    {
      id: "proj-1",
      name: "DevStream",
      description: "A developer-focused content curation platform utilizing AI to aggregate and summarize top technical blogs. Built with Next.js, FastAPI, and Tailwind CSS.",
      url: "https://github.com/alexrivera/devstream",
      technologies: ["React", "FastAPI", "Gemini API", "PostgreSQL"]
    }
  ],
  themeConfig: DEFAULT_THEME,
  templateId: "modern",
  createdAt: Date.now(),
  updatedAt: Date.now(),
  userId: "sample-user"
};
